version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: price_history
    ports:
      - 8282:80
    volumes:
      - .:/srv/price_history
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: price_history
      DB_USERNAME: dbuser123
      DB_PASSWORD: password
  mysql:
    image: mysql:5.7
    command: --max_allowed_packet=32505856
    ports:
      - 13306:3306
    volumes:
      - ./dump/price_history_2019-12-12.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_DATABASE: price_history
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password